/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as CompetencesRouteImport } from './routes/competences'
import { Route as CandidatureRouteImport } from './routes/candidature'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsShieldNanoRouteImport } from './routes/projects.shield-nano'
import { Route as ProjectsRegulationTemperatureRouteImport } from './routes/projects.regulation-temperature'
import { Route as ProjectsMultimetreRouteImport } from './routes/projects.multimetre'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetencesRoute = CompetencesRouteImport.update({
  id: '/competences',
  path: '/competences',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatureRoute = CandidatureRouteImport.update({
  id: '/candidature',
  path: '/candidature',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsShieldNanoRoute = ProjectsShieldNanoRouteImport.update({
  id: '/shield-nano',
  path: '/shield-nano',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsRegulationTemperatureRoute =
  ProjectsRegulationTemperatureRouteImport.update({
    id: '/regulation-temperature',
    path: '/regulation-temperature',
    getParentRoute: () => ProjectsRoute,
  } as any)
const ProjectsMultimetreRoute = ProjectsMultimetreRouteImport.update({
  id: '/multimetre',
  path: '/multimetre',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/candidature': typeof CandidatureRoute
  '/competences': typeof CompetencesRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/multimetre': typeof ProjectsMultimetreRoute
  '/projects/regulation-temperature': typeof ProjectsRegulationTemperatureRoute
  '/projects/shield-nano': typeof ProjectsShieldNanoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/candidature': typeof CandidatureRoute
  '/competences': typeof CompetencesRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/multimetre': typeof ProjectsMultimetreRoute
  '/projects/regulation-temperature': typeof ProjectsRegulationTemperatureRoute
  '/projects/shield-nano': typeof ProjectsShieldNanoRoute
}
export interface FileRoutesByIdextends {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/candidature': typeof CandidatureRoute
  '/competences': typeof CompetencesRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/multimetre': typeof ProjectsMultimetreRoute
  '/projects/regulation-temperature': typeof ProjectsRegulationTemperatureRoute
  '/projects/shield-nano': typeof ProjectsShieldNanoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/candidature'
    | '/competences'
    | '/projects'
    | '/projects/multimetre'
    | '/projects/regulation-temperature'
    | '/projects/shield-nano'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/candidature'
    | '/competences'
    | '/projects'
    | '/projects/multimetre'
    | '/projects/regulation-temperature'
    | '/projects/shield-nano'
  id:
    | '__root__'
    | '/'
    | '/candidature'
    | '/competences'
    | '/projects'
    | '/projects/multimetre'
    | '/projects/regulation-temperature'
    | '/projects/shield-nano'
  fileRoutesById: FileRoutesByIdextends
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CandidatureRoute: typeof CandidatureRoute
  CompetencesRoute: typeof CompetencesRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competences': {
      id: '/competences'
      path: '/competences'
      fullPath: '/competences'
      preLoaderRoute: typeof CompetencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidature': {
      id: '/candidature'
      path: '/candidature'
      fullPath: '/candidature'
      preLoaderRoute: typeof CandidatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/shield-nano': {
      id: '/projects/shield-nano'
      path: '/shield-nano'
      fullPath: '/projects/shield-nano'
      preLoaderRoute: typeof ProjectsShieldNanoRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/regulation-temperature': {
      id: '/projects/regulation-temperature'
      path: '/regulation-temperature'
      fullPath: '/projects/regulation-temperature'
      preLoaderRoute: typeof ProjectsRegulationTemperatureRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/multimetre': {
      id: '/projects/multimetre'
      path: '/multimetre'
      fullPath: '/projects/multimetre'
      preLoaderRoute: typeof ProjectsMultimetreRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsMultimetreRoute: typeof ProjectsMultimetreRoute
  ProjectsRegulationTemperatureRoute: typeof ProjectsRegulationTemperatureRoute
  ProjectsShieldNanoRoute: typeof ProjectsShieldNanoRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsMultimetreRoute: ProjectsMultimetreRoute,
  ProjectsRegulationTemperatureRoute: ProjectsRegulationTemperatureRoute,
  ProjectsShieldNanoRoute: ProjectsShieldNanoRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CandidatureRoute: CandidatureRoute,
  CompetencesRoute: CompetencesRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
